### ISSUE TITLE
create.barplot: how to change fontsize of text.above.bars ?

### ISSUE THREAD

**Issue by jarbet** [uclahs-cds/public-R-BoutrosLab-plotting-general#101]
For `create.barplot`, how do you change the fontsize of `text.above.bars` ?  Is there an existing argument that can do this?

The text I am trying to add overlaps the bars so you can't read it.  I would like to try making the text size smaller.

**Comment by stefaneng** [comment]
There does not seem to be an option. See the relevant lines of code here:

https://github.com/uclahs-cds/public-R-BoutrosLab-plotting-general/blob/main/R/create.barplot.R#L233-L249

Should be a simple fix, I'll open a PR soon.

**Comment by stefaneng** [comment]
@jarbet you can test PR #102 to see if that fixes your issue.
