### ISSUE TITLE
coding error that prevents polygonplot group medians from having different lwd

### ISSUE THREAD

**Issue by lydiayliu** [uclahs-cds/public-R-BoutrosLab-plotting-general#13]
https://github.com/uclahs-cds/public-R-BoutrosLab-plotting-general/blob/889ceb88ccb2b567037ea4da0be2726dfe5caa41/R/create.polygonplot.R#L336-L349

There is a bug here in lines #347-349

You can see that lines #338-340 and #342-344 have this nice `if else` structure for `border.col` and `median.col` that enables each group in the polygon to have a different border and median colour.

This `if else` structure is somehow broken/missing in line #346, and thus inputting a `median.lty` with `length != 1` leads to an error with lattice.

It seems to be an error with copy and pasting, since the `else` statement for `median.lty` is somehow in #347-349 following the `if` statement for `median.lwd`. As a result, inputting a `median.lwd` with `length != 1` also leads to an error with lattice...

Easy fix as

```
				median.lty <- if (length(median.lty) == 1) { rep(median.lty, length(subscripts)); } else {
					as.character(factor(x = groups, labels = median.lty));
					}
				median.lwd <- if (length(median.lwd) == 1) { rep(median.lwd, length(subscripts)); } else {
					as.character(factor(x = groups, labels = median.lwd));
					}
```

**Comment by dan-knight** [comment]
Good catch @lydiayliu. Do you think this could become a small utility function instead of copying/pasting? There's a lot of places in this package that break the [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) rule of programming. Maybe something like:

```
prepare.values <- function(values) {
  if (length(values)) == 1 { 
    rep(values, length(subscripts)); 
  } else {
    as.character(factor(x = groups, labels = values));
    }
    
```

Then we could handle all plot values a once like:

```
median.lty <- prepare.values(median.lty);
median.lwd <- prepare.values(median.lwd);
...
...
```

**Comment by lydiayliu** [comment]
that's a great idea! It's all yours XD

**Comment by dan-knight** [comment]
@lydiayliu Could you create a simple example/test case for this please? I've written a fix based on what we discussed above, but I'm having trouble reproducing the error. Thanks!
