### ISSUE TITLE
create.histogram does not have the option to add additional text

### ISSUE THREAD

**Issue by lydiayliu** [uclahs-cds/public-R-BoutrosLab-plotting-general#21]
as titled, was wondering if add.text could be added to create.histogram for standardization. (of course one could achieve the same functions by plotting a barplot...)

**Comment by dan-knight** [comment]
Sounds doable! If possible, could you provide an example image? It would be helpful to see a visual example of the text you have in mind.

**Comment by lydiayliu** [comment]
I think the exact same functions as any of the other plots would be good! For example in this barplot

```
# Change bar thickness and add text labels
create.barplot(
    #
    # needs sequential x-axis
    formula = values ~ 1:15,
    data = error.data,
    y.error.up = error.data$error,
    xaxis.lab = error.data$genes,
    main = 'Error bars',
    xlab.lab = 'Gene',
    ylab.lab = 'Change in Expression',
    ylimits = c(0,14),
    yat = seq(0,14,2),
    xaxis.cex = 1,
    yaxis.cex = 1,
    xaxis.rot = 45,
    xlab.cex = 1.5,
    ylab.cex = 1.5,
    xaxis.fontface = 1,
    yaxis.fontface = 1,
    description = 'Barplot created by BoutrosLab.plotting.general'
    );
```

![image](https://user-images.githubusercontent.com/10492815/157947204-4a5f22b3-49e7-4349-8324-5911d383682d.png)

This probably should be a different issue, but I also wish the text justification could be adjusted. All text is by default `center`, but really `left` justification would help a lot more with plot consistency

**Comment by jarbet** [comment]
I also had the issue of wanting to add text to a histogram.

@stefaneng came up with this solution for now:

```
library(BoutrosLab.plotting.general);

set.seed(123);
histogram <- create.histogram(
    x = rnorm(5000)
    );

histogram + layer(panel.text(x = -2, y = 15, labels = 'Hello', fontface = 'bold'));
```

**Comment by stefaneng** [comment]
Full example for the temporary solution to include multiple text labels:

```R
library(BoutrosLab.plotting.general);

set.seed(13);
N <- 1000;
data <- cbind.data.frame(value = rnorm(N));
histogram1 <- create.histogram(
  x = data$value,
  type = 'count',
  ylab.label = 'Count',
  xlab.label = 'value'
  );

add.text.layer <- layer({
	# Pass any number of panel.text  into the expression
	panel.text(x = 3, y = 100, labels = 'Label 1', fontface = 'bold')
	panel.text(x = 3, y = 150, labels = 'Label 2', fontface = 'bold')
	panel.text(x = 3, y = 200, labels = 'Label 3', fontface = 'bold')
	});

# Merge the panels together
histogram1 + add.text.layer;
```

![image](https://user-images.githubusercontent.com/1639487/204911192-5d11d13a-a1a4-41e3-97c9-67a8e689c1b3.png)
