### ISSUE TITLE
Why is the API documentation not made public?

### ISSUE THREAD

**Issue by lydiayliu** [uclahs-cds/public-R-BoutrosLab-plotting-general#37]
I have heard several reports from people trying to use BPG that are not from the Boutros Lab. They all say that the lack of documentation really hinders the uptake.

Any reasons why the web API is not hosted for public use? By web API I mean: https://development.boutroslab.net/API/BoutrosLab.plotting.general/5.9.2/. As far as I'm aware it requires VPN access.

Although the reference manual is made available through CRAN and essentially contains the same information, I believe most people internally use the API for easy access and most importantly the visualization of the plots. I've literally never used the reference manual myself and believe it is hard to navigate for new users.

**Comment by stefaneng** [comment]
@lydiayliu gh-pages is now live: https://uclahs-cds.github.io/public-R-BoutrosLab-plotting-general

**Comment by lydiayliu** [comment]
@stefaneng oh this is awesome, thank you!!!

I've passed the link to external users and can confirm that it is accessible. On feedback I got was that there used to be another page (hosted back in Toronto) that contains code + plot of publication figures. Is that something that we can host again on the same documentation site as well?

**Comment by stefaneng** [comment]
> > @lydiayliu gh-pages is now live: https://uclahs-cds.github.io/public-R-BoutrosLab-plotting-general
> 
> The doi link is broken: https://www.doi.org/%2010.1186/s12859-019-2610-2
> 
> I think the correct link is: https://doi.org/10.1186%2Fs12859-019-2610-2

Good catch. This was rendered directly from DESCRIPTION which had an extra space.

**Comment by stefaneng** [comment]
> @stefaneng oh this is awesome, thank you!!!
> 
> I've passed the link to external users and can confirm that it is accessible. One feedback I got was that there used to be another page (hosted back in Toronto) that contains code + plot of publication figures. Is that something that we can host again on the same documentation site as well?

@lydiayliu I'm not sure what page that is but if we convert it to a vignette in this repo then it will render on the API page as well.

**Comment by tyamaguchi-ucla** [comment]
> > @stefaneng oh this is awesome, thank you!!!
> > I've passed the link to external users and can confirm that it is accessible. One feedback I got was that there used to be another page (hosted back in Toronto) that contains code + plot of publication figures. Is that something that we can host again on the same documentation site as well?
> 
> @lydiayliu I'm not sure what page that is but if we convert it to a vignette in this repo then it will render on the API page as well.

I think she meant this page. We used to have a webpage for this back in Canada. https://confluence.mednet.ucla.edu/display/BOUTROSLAB/Plotting+Hall+of+Fame

**Comment by lydiayliu** [comment]
OMG thank you @tyamaguchi-ucla ! That's the one. How difficult would it be to host it for the public? I can see that the code is on github

**Comment by stefaneng** [comment]
@lydiayliu If we pull the examples into a simple vignette then it can be rendered as a page on the API docs.

**Comment by lydiayliu** [comment]
Sure I will create an issue :D
