### ISSUE TITLE
No TIFF support in this version of R

### ISSUE THREAD

**Issue by ricorona** [uclahs-cds/public-R-BoutrosLab-plotting-general#51]
When I try to use the function create.multipanelplot, to save the resulting figure as a "tiff", it gives me the error: "In dev.off() : No TIFF support in this version of R". I can see that when I use the R function "capabilities()", the flag for "tiff" is "FALSE". I have a Mac with Apple M1 Pro Chip. This is my session info:
--------------------------------------------------------------------------------------------------------------------------------
R version 4.2.1 (2022-06-23)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Monterey 12.6

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] grid      parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] BoutrosLab.plotting.general_7.0.3 hexbin_1.28.2                     cluster_2.1.4                     latticeExtra_0.6-30              
 [5] lattice_0.20-45                   doMC_1.3.8                        iterators_1.0.14                  foreach_1.5.2                    
 [9] readxl_1.4.1                      stringr_1.4.1                     BoutrosLab.utilities_1.9.10      

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.9         cellranger_1.1.0   compiler_4.2.1     pillar_1.8.1       RColorBrewer_1.1-3 class_7.3-20       tools_4.2.1       
 [8] tibble_3.1.8       lifecycle_1.0.2    gtable_0.3.1       pkgconfig_2.0.3    png_0.1-7          rlang_1.0.6        cli_3.4.1         
[15] rstudioapi_0.14    interp_1.1-3       gridExtra_2.3      e1071_1.7-11       vctrs_0.4.2        glue_1.6.2         jpeg_0.1-9        
[22] fansi_1.0.3        deldir_1.0-6       magrittr_2.0.3     codetools_0.2-18   MASS_7.3-58.1      utf8_1.2.2         stringi_1.7.8     
[29] proxy_0.4-27
--------------------------------------------------------------------------------------------------------------------------------

Thanks

**Comment by ricorona** [comment]
Sure, here is an example taken from the PlottingGuide.pdf:

scatter.data <- data.frame(
  sample.one = microarray[1:800,1],
  sample.two = microarray[1:800,2]
);
create.scatterplot(
  formula = sample.two ~ sample.one,
  data = scatter.data,
  filename = 'scatterplot.tiff'
);

This gives the message:

**Warning message:
In dev.off() : No TIFF support in this version of R**

And well, it is not an error, but the figure is not generated.

I can change the filename to pdf instead of tiff and it works "fine", but for some really dense figures, e.g., heatmaps, tiffs just look better than PDFs.

I think this is not a problem with BoutrosLab.plotting.general package itself, but the compatibility with my environment. But I do not know how to fix it.

Thanks,

**Comment by pboutros** [comment]
Got it, so this affects all plotting functions or just create.multipanelplot()?  As a work-around while we debug, maybe create a PNG or JPEG with sufficient dpi?

________________________________

UCLA HEALTH SCIENCES IMPORTANT WARNING: This email (and any attachments) is only intended for the use of the person or entity to which it is addressed, and may contain information that is privileged and confidential. You, the recipient, are obligated to maintain it in a safe, secure and confidential manner. Unauthorized redisclosure or failure to maintain confidentiality may subject you to federal and state penalties. If you are not the intended recipient, please immediately notify us by return email, and delete this message from your computer.

**Comment by ricorona** [comment]
It affects all plotting functions. Sure, I can create PNG/JPEG.

Thanks,

**Comment by pboutros** [comment]
Can you create TIFFs using base R, rather than via BPG?

**Comment by pboutros** [comment]
Got it, so it’s not a BPG issue but a base R one, or maybe even a MacOS issue.  I’d try one of the R forums (https://community.rstudio.com/ or https://stackoverflow.com/questions/tagged/r perhaps?).

________________________________

UCLA HEALTH SCIENCES IMPORTANT WARNING: This email (and any attachments) is only intended for the use of the person or entity to which it is addressed, and may contain information that is privileged and confidential. You, the recipient, are obligated to maintain it in a safe, secure and confidential manner. Unauthorized redisclosure or failure to maintain confidentiality may subject you to federal and state penalties. If you are not the intended recipient, please immediately notify us by return email, and delete this message from your computer.

**Comment by ricorona** [comment]
Thanks, will do!

**Comment by madisonjordan** [comment]
I wonder if it would work if you use the R-4.2.1-arm64.pkg from [cran](https://cran.r-project.org)
It appears you have the intel one installed. 
> Platform: x86_64-apple-darwin17.0 (64-bit)

As far as I know, the M1 apple chip is an "arm" architecture not a "x86_64"

**Comment by ricorona** [comment]
BINGO!!!! 

Thanks so much!! :)

**Comment by dan-knight** [comment]
Awesome! Well done @madisonjordan. I think it would be worth including this (as well as other related "gotchas") in the user guide.

**Comment by pboutros** [comment]
NICE CATCH!!!
