### ISSUE TITLE
create.barplot y-axis labels wrong when plot.horizontal and sorting

### ISSUE THREAD

**Issue by jarbet** [uclahs-cds/public-R-BoutrosLab-plotting-general#63]
The `create.barplot` y-axis labels are in the wrong order when `plot.horizontal = TRUE` and `sample.order = 'decreasing'` (or `increasing`).

Example:

```
library(BoutrosLab.plotting.general);

data(mtcars);
mtcars$car <- rownames(mtcars);
rownames(mtcars) <- NULL;
mtcars <- mtcars[, c('car', 'wt')];
mtcars <- mtcars[order(mtcars$wt, decreasing = TRUE),];
```

Notice **Lincoln Continental** has the largest weight:

```
> head(mtcars);
                   car    wt
16 Lincoln Continental 5.424
17   Chrysler Imperial 5.345
15  Cadillac Fleetwood 5.250
12          Merc 450SE 4.070
25    Pontiac Firebird 3.845
24          Camaro Z28 3.840
```

**Horizonal barplot, sorting samples in decreasing order:**

* Lincoln Continental should have the largest weight, but it shows as having the smallest weight. The labels no longer match the values:

```
create.barplot(
    car ~ wt,
    data = mtcars,
    sample.order = 'decreasing',
    plot.horizontal = TRUE,
    yaxis.cex = 0.5,
    );
```
![test1](https://user-images.githubusercontent.com/103967480/206057522-d2d4cb41-1013-4a97-94bf-065ee4355ecd.png)

**Notes**:

* The labels are also wrong if using `sample.order = 'increasing'`
* This bug only seems to happen when `plot.horizontal = TRUE`, which I need for the multipanel plot I am making

**Comment by stefaneng** [comment]
@jarbet Workaround for now:
```r
create.barplot(
    car ~ wt,
    data = mtcars,
#     sample.order = 'decreasing',
    disable.factor.sorting = TRUE, # Need to add this for manual ordering
    yaxis.lab = mtcars$car,
    plot.horizontal = TRUE,
    yaxis.cex = 0.5
    );
```

![image](https://user-images.githubusercontent.com/1639487/206062331-553cea8c-c20f-4aab-a373-15a71e50ec87.png)


Seems like there is a reverse where there shouldn't be somewhere in the `plot.horizontal` and `sample.order` code:
https://github.com/uclahs-cds/public-R-BoutrosLab-plotting-general/blob/main/R/create.barplot.R#L691-L744
