### ISSUE TITLE
Violin plot draws violin for constant values

### ISSUE THREAD

**Issue by Faizal-Eeman** [uclahs-cds/public-R-BoutrosLab-plotting-general#84]
I’ve been trying to draw a violin plot with constant values with `create.violin()` and theoretically I’d expect the plot from BPG to look like a straight line as seen in the plot generated by ggplot2. But I see that BPG creates longer tails at both violin ends for constant values.

Example dataset:
```
> simple.data <- data.frame(
    values = rep(100, 5),
    variable = rep("a", 5)
    );

> simple.data;
  values variables
1 100 a
2 100 a
3 100 a
4 100 a
5 100 a
```

Plot from BPG:
> create.violinplot(formula = values ~ variable, data = simple.data, ylimits = c(-20,120));

![bpg_violin](https://user-images.githubusercontent.com/68152431/213083691-8cc0ff64-50d6-4fd5-9de2-21f3b5de8e57.png)

Plot from ggplot2:
> ggplot(simple.data, aes(x=variable, y=values)) + geom_violin() + ylim(-20, 120);

![ggplot_violin](https://user-images.githubusercontent.com/68152431/213083762-fc9047eb-cca4-4908-8dc0-35aa62da6c3d.png)

Any idea why BPG is generating a violin instead of a line?

**Comment by pboutros** [comment]
I think overall it mostly doesn't make sense to do a violinplot when there is variance=zero, and I almost think the correct BPG behaviour would be to error, but I assume we're inheriting the lattice functionality on this?  I think ultimately the difference with ggplot is how the smoothing is done.  For internal purposes, I'd recommend using a different visualization strategy if variance=0 is expected to be routine.

**Comment by stefaneng** [comment]
We do inherit the lattice functionality but there is a patched version in our code of [`panel.violin` here](https://github.com/uclahs-cds/public-R-BoutrosLab-plotting-general/blob/main/R/create.violinplot.R#L61-L193). Though the behavior of the constant variance case is the same in both BPG and lattice. It looks like it comes down to `stats::density` function call that still creates a kernel density estimate even when there is no variance.
