### ISSUE TITLE
Remove BoutrosLab.plotting.general from function table in README

### ISSUE THREAD

**Issue by madisonjordan** [uclahs-cds/public-R-BoutrosLab-plotting-general#88]
Reove the `BoutrosLab.plotting.general` and `BoutrosLab.plotting.general-package` from the first row in the function table in the README and move it above the table.

**Comment by stefaneng** [comment]
I think that entire Rd page can be removed as well: https://github.com/uclahs-cds/public-R-BoutrosLab-plotting-general/blob/main/man/BoutrosLab.plotting.general-package.Rd since it is out of date and adds no additional information. I'll open a new issue for that.

**Comment by forbiddenpersimmon** [comment]
> I think that entire Rd page can be removed as well: https://github.com/uclahs-cds/public-R-BoutrosLab-plotting-general/blob/main/man/BoutrosLab.plotting.general-package.Rd since it is out of date and adds no additional information. I'll open a new issue for that.

Should I just remove the `Boutros.plotting.general` links from the table completely then as it's the same info?

**Comment by stefaneng** [comment]
@forbiddenpersimmon Yup, remove both `BoutrosLab.plotting.general` and `BoutrosLab.plotting.general-package` from the table (that entire row).
